services:
  - type: web
    name: api-financas
    env: python
    plan: free
    buildCommand: ""
    startCommand: "gunicorn src.main_mysql:app"
    envVars:
      - key: FLASK_ENV
        value: production
